kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "test-pipeline"
spec:
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          openshiftBuild bldCfg: '{{ app_name }}'
          openshiftVerifyBuild bldCfg: '{{ app_name }}'
        }
