kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "test-pipeline"
spec:
  triggers:
  - type: GitHub
    github:
      secret: secret101
  - type: Generic
    generic:
      secret: secret101
spec:
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          openshiftBuild bldCfg: '{{ app_name }}'
          openshiftVerifyBuild bldCfg: '{{ app_name }}'
        }
