---
# mangler login
- hosts: GOTOdemo
  remote_user: jborella
  vars:
    app_name: hello-world
    app_namespace: ansibletestproject
    webhook_secret: secret1234
    gituser: jacobborella
  tasks:
  - name: Create project
    oc_project:
      name: "{{ app_namespace }}"
      displayName: GOTO Ansible Demo
      description: Demo of using Ansible for provisioning servers
      state: present
  - name: Create secret in the project
    block:
    - template:
        src: templates/secret.yaml
        dest: /tmp/secret.yaml
        mode: 0600
    - oc_template:
        namespace: "{{ app_namespace }}"
        filename: /tmp/secret.yaml
        state: present
    always:
    - file:
        path: /tmp/secret.yaml
        state: absent
  - name: Create pipeline template file
    template:
      src: templates/pipeline.yaml
      dest: /tmp/pipeline.yaml
      mode: 0644
  - name: Apply pipeline template
    oc_template:
      namespace: "{{ app_namespace }}"
      filename: /tmp/pipeline.yaml
      state: present
    register: result
  - name: Create openjdk template file
    template:
      src: templates/openjdk.json
      dest: /tmp/openjdk.json
      mode: 0644
  - name: Apply openjdk template
    oc_template:
      namespace: "{{ app_namespace }}"
      filename: /tmp/openjdk.json
      state: present
  - name: Create app
    oc_app:
      name: "{{ app_name }}"
      namespace: "{{ app_namespace }}"
      template: openjdk18-web-basic-s2i
      template-parameters: SOURCE_REPOSITORY_URL=https://github.com/jacobborella/myproject.git,CONTEXT_DIR=,APPLICATION_NAME=hello-world
      state: present
  - name: Set environment variable
    oc_env:
      name: "{{ app_name }}"
      namespace: "{{ app_namespace }}"
      resource: dc
      key: GREETING
      value: Hello GOTO
      state: present
  - name: Set environment variable
    oc_env:
      name: "{{ app_name }}"
      namespace: "{{ app_namespace }}"
      resource: dc
      key: SPRING_CONFIG_LOCATION
      value: /data/application.properties
      state: absent
  - name: Setup git
    github_hooks:
      action: create
      hookurl: https://li1645-194.members.linode.com:8443{{result.meta.selfLink}}/webhooks/webhook_secret/github
      user: '{{ gituser }}'
      oauthkey: '{{ oauthkey }}'
      repo: https://api.github.com/repos/jacobborella/myproject
