---
# mangler login
- hosts: OCPmasters
  remote_user: jborella
  vars:
    app_name: hello-world
    webhook_secret: secret1234
    gituser: jacobborella
  tasks:
  - name: Include secret vars
    include_vars:
      file: secret.yaml
  - name: Create project
    oc_project:
      name: ansibletestproject
      displayName: GOTO Ansible Demo
      description: Demo of using Ansible for provisioning servers
      state: present
  - name: Create app
    oc_app:
      name: "{{ app_name }}"
      namespace: ansibletestproject
      git-repo: https://github.com/openshift/cakephp-ex.git
      state: present
  - name: Create OpenJDK template file
    template:
      src: templates/openjdk.json
      dest: /tmp/openjdk.json
      mode: 0644
  - name: Create pipeline template file
    template:
      src: templates/pipeline.yaml
      dest: /tmp/pipeline.yaml
      mode: 0644
  - name: Apply OpenJDK template
    oc_template:
      namespace: ansibletestproject
      filename: /tmp/openjdk.json
      state: absent
  - name: Apply pipeline template
    oc_template:
      namespace: ansibletestproject
      filename: /tmp/pipeline.yaml
      state: present
    register: result
  - name: Setup git
    github_hooks:
      action: create
      hookurl: https://li1645-194.members.linode.com:8443{{result.meta.selfLink}}/webhooks/webhook_secret/github
      user: '{{ gituser }}'
      oauthkey: '{{ oauthkey }}'
      repo: https://api.github.com/repos/jacobborella/myproject
